baseURL = 'https://example.org/'
languageCode = 'en-us'
title = 'SECURITY-BUFFOR'

[[menus.main]]
name = 'Home'
pageRef = '/'
weight = 10



[[menus.main]]
name = 'Posts'
pageRef = '/posts'
weight = 20

[[menus.main]]
name = 'Tags'
pageRef = '/tags'
weight = 30

[module]
  [module.hugoVersion]
    extended = false
    min = "0.116.0"

[[menus.main]]
name = 'Contact'
pageRef = '/contact'
weight = 30

[[menu.main]]
name = 'Contact'
pageRef = '/contact'
weight = 30